### ISSUE TITLE
Fatal error when trying to print an array value with the document `custom_field()` method

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#630]
[A user](https://wordpress.org/support/topic/error-with-advance-custom-fields/) reported a fatal error when tried to pass an array to the document `custom_field()` method. It is caused by the `nl2br()` function, since it does not support an array type.

See the user stack trace below:

```
Fatal error: nl2br(): Argument #1 ($string) must be of type string, array given
/home/customer/www/demo-staging.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document-methods.php (257)
#0 /home/customer/www/demo-staging.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document-methods.php(257): nl2br(Array)
#1 /home/customer/www/demo-staging.com/public_html/wp-content/themes/helter-child/woocommerce/pdf/Zeno/invoice.php(116): WPO\WC\PDF_Invoices\Documents\Order_Document_Methods->custom_field('dispositivo_med...')
#2 /home/customer/www/demo-staging.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(976): include('/home/customer/...')
#3 /home/customer/www/demo-staging.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(879): WPO\WC\PDF_Invoices\Documents\Order_Document->render_template('/home/customer/...', Array)
#4 /home/customer/www/demo-staging.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(834): WPO\WC\PDF_Invoices\Documents\Order_Document->get_html()
#5 /home/customer/www/demo-staging.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(901): WPO\WC\PDF_Invoices\Documents\Order_Document->get_pdf()
#6 /home/customer/www/demo-staging.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-main.php(466): WPO\WC\PDF_Invoices\Documents\Order_Document->output_pdf('inline')
#7 /home/customer/www/demo-staging.com/public_html/wp-includes/class-wp-hook.php(310): WPO\WC\PDF_Invoices\Main->generate_pdf_ajax('')
#8 /home/customer/www/demo-staging.com/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#9 /home/customer/www/demo-staging.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /home/customer/www/demo-staging.com/public_html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_generat...')
#11 {main}
```

**Comment by dwalkerpriv** [comment]
@YordanSoares i'm not getting this error. i have done a setup a close as possible to his. When I echo the field, if it's an array, nothing is printed. But if it's a string, it's printed normally. Also imploding the array values like his old code prints the values as well.

The multiselect field on the order edits page:

![Screenshot 2023-10-24 184850](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/62675729/629e7d5a-82bf-4944-a7a5-f73b807d1f93)

The meta keys in the order

![Screenshot 2023-10-24 184914](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/62675729/0a20a2c4-1abf-43c8-a75c-55d4f37e0f61)

**Comment by YordanSoares** [comment]
@MohamadNateqi please note that you have to enable the debug output in the Status tab, if you're testing this on PHP 7+, and you should see it as a warning, but in PHP 8+ it is treated as a fatal error.

To make it easier and faster to test, try with this code snippet:

```php
add_action( 'wpo_wcpdf_after_customer_notes', function( $document_type, $order ) {
	if ( ! $order->get_meta ( 'cities' ) ) {
		$cities = [ 'Madrid', 'Lisbon', 'Tehran' ];
		$order->update_meta_data( 'cities', $cities );
	}
	$invoice = wcpdf_get_document( 'invoice', $order );
	$invoice->custom_field( 'cities' );
}, 10, 2 );
```
